version: "2"
services:
  database: 
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
  app:
    build: .
    environment:
      DB_HOST: database
      DB_USER: root
      DB_PASS: password
    links:
      - database
    ports:
      - "80"
